# -*- coding: utf-8 -*-
"""app2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oQwn5JIohzBiSWAUrC8lY1uATwW9SRp
"""

```python id="x9m2qd"
import streamlit as st
import sympy as sp

# =========================
# CONFIGURAÇÃO
# =========================

st.set_page_config(
    page_title="IntegralDB",
    page_icon="💾",
    layout="centered"
)

# =========================
# ESTILO CYBERPUNK
# =========================

st.markdown("""
<style>

.stApp {
    background-color: #000000;
    color: #00FF00;
}

h1, h2, h3, h4 {
    color: #00FF00;
}

.stButton>button {
    background-color: #001100;
    color: #00FF00;
    border: 1px solid #00FF00;
}

.stTextInput>div>div>input {
    background-color: #001100;
    color: #00FF00;
}

</style>
""", unsafe_allow_html=True)

# =========================
# VARIÁVEIS
# =========================

x = sp.symbols('x')

# =========================
# SESSION STATE
# =========================

if "fase" not in st.session_state:
    st.session_state.fase = 1

if "pontos" not in st.session_state:
    st.session_state.pontos = 0

if "vidas" not in st.session_state:
    st.session_state.vidas = 3

# =========================
# FASES
# =========================

fases = {

    1: {
        "nome": "CACHE DE LOGS",
        "historia": "Restaure os registros apagados do servidor.",
        "funcao": x**2,
        "pontos": 100
    },

    2: {
        "nome": "TABELAS FRAGMENTADAS",
        "historia": "Reconstrua as tabelas do banco de dados.",
        "funcao": 3*x**2 + 5,
        "pontos": 150
    },

    3: {
        "nome": "FIREWALL MATEMÁTICO",
        "historia": "Desative a criptografia do firewall.",
        "funcao": 3/x + x**2,
        "pontos": 250
    },

    4: {
        "nome": "NÚCLEO DE DESCRIPTOGRAFIA",
        "historia": "Use substituição para recuperar os dados.",
        "funcao": 2*x*(x**2 + 1)**5,
        "pontos": 500,
        "substituicao": True,
        "u_correto": "x**2 + 1"
    },

    5: {
        "nome": "MAINFRAME CENTRAL",
        "historia": "Integração por partes necessária.",
        "funcao": x*sp.exp(x),
        "pontos": 1000,
        "partes": True,
        "u_correto": "x",
        "dv_correto": "exp(x)"
    }
}

# =========================
# SIDEBAR
# =========================

st.sidebar.title("💾 STATUS")

st.sidebar.metric(
    "Pontuação",
    st.session_state.pontos
)

st.sidebar.metric(
    "Vidas",
    st.session_state.vidas
)

st.sidebar.progress(
    st.session_state.fase / 5
)

# =========================
# GAME OVER
# =========================

if st.session_state.vidas <= 0:

    st.error("☠️ SISTEMA COMPROMETIDO")

    st.stop()

# =========================
# JOGO
# =========================

if st.session_state.fase <= 5:

    fase = fases[st.session_state.fase]

    st.title("💾 IntegralDB")

    st.subheader(
        f"🔥 FASE {st.session_state.fase} — {fase['nome']}"
    )

    st.write(fase["historia"])

    st.latex(
        r"\int " + sp.latex(fase["funcao"]) + r"\,dx"
    )

    # =====================
    # FASE 4 - SUBSTITUIÇÃO
    # =====================

    if "substituicao" in fase:

        st.info("Escolha corretamente a substituição u")

        escolha_u = st.radio(
            "Qual deve ser u?",
            [
                "x**2 + 1",
                "2*x",
                "x**5"
            ]
        )

    # =====================
    # FASE 5 - POR PARTES
    # =====================

    if "partes" in fase:

        st.info("Escolha corretamente u e dv")

        escolha_u = st.radio(
            "Escolha u",
            [
                "x",
                "exp(x)"
            ]
        )

        escolha_dv = st.radio(
            "Escolha dv",
            [
                "x",
                "exp(x)"
            ]
        )

        st.latex(
            r"\int u\,dv = uv - \int v\,du"
        )

    # =====================
    # RESPOSTA
    # =====================

    resposta = st.text_input(
        "Digite sua integral:"
    )

    st.caption(
        "Você pode usar ^ ou **"
    )

    # =====================
    # BOTÃO
    # =====================

    if st.button("Enviar"):

        try:

            # Corrige ^
            resposta = resposta.replace("^", "**")

            resposta_usuario = sp.sympify(resposta)

            derivada_usuario = sp.diff(
                resposta_usuario,
                x
            )

            integrando_original = fase["funcao"]

            correto = (
                sp.simplify(
                    derivada_usuario
                    - integrando_original
                ) == 0
            )

            # =================
            # VALIDA SUBSTITUIÇÃO
            # =================

            if "substituicao" in fase:

                correto = (
                    correto and
                    escolha_u == fase["u_correto"]
                )

            # =================
            # VALIDA POR PARTES
            # =================

            if "partes" in fase:

                correto = (
                    correto and
                    escolha_u == fase["u_correto"] and
                    escolha_dv == fase["dv_correto"]
                )

            # =================
            # RESULTADO
            # =================

            if correto:

                st.success(
                    "✅ BLOCO RESTAURADO"
                )

                st.session_state.pontos += (
                    fase["pontos"]
                )

                st.session_state.fase += 1

            else:

                st.error(
                    "❌ FALHA NA DESCRIPTOGRAFIA"
                )

                st.session_state.vidas -= 1

        except:

            st.warning(
                "⚠️ Expressão inválida."
            )

# =========================
# FINAL
# =========================

else:

    st.success(
        "👑 MAINFRAME RESTAURADO"
    )

    st.balloons()

    st.write(
        f"Pontuação Final: {st.session_state.pontos}"
    )

    if st.session_state.pontos >= 1800:

        st.success(
            "🏆 RANK S — ANALISTA LENDÁRIO"
        )

    elif st.session_state.pontos >= 1200:

        st.success(
            "🥇 RANK A — ESPECIALISTA"
        )

    else:

        st.success(
            "🥈 RANK B — ANALISTA"
        )
```