# -*- coding: utf-8 -*-
"""integraldb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ne9RJVODw5DBUJ-FSaZjEHwAzgmNDj3w
"""

# =====================================================
# INTEGRALDB — VERSÃO STREAMLIT
# =====================================================

import streamlit as st
import sympy as sp
import numpy as np
import matplotlib.pyplot as plt

# =====================================================
# CONFIGURAÇÃO
# =====================================================

st.set_page_config(
    page_title="IntegralDB",
    page_icon="💾",
    layout="centered"
)

# =====================================================
# ESTILO
# =====================================================

st.markdown("""
<style>

.stApp {
    background-color: #000000;
    color: #00FF00;
}

h1, h2, h3 {
    color: #00FF00;
}

.stButton>button {
    background-color: #001100;
    color: #00FF00;
    border: 1px solid #00FF00;
}

.stTextInput>div>div>input {
    background-color: #001100;
    color: #00FF00;
}

</style>
""", unsafe_allow_html=True)

# =====================================================
# VARIÁVEL
# =====================================================

x = sp.symbols('x')

# =====================================================
# SESSION STATE
# =====================================================

if "fase" not in st.session_state:
    st.session_state.fase = 1

if "pontos" not in st.session_state:
    st.session_state.pontos = 0

if "vidas" not in st.session_state:
    st.session_state.vidas = 10

# =====================================================
# FASES
# =====================================================

fases = {

    1: {
        "nome": "CACHE DE LOGS",

        "historia":
            "Os registros do servidor principal "
            "foram parcialmente corrompidos.",

        "enunciado":
            "O sistema monitora a taxa de "
            "crescimento do armazenamento "
            "de logs ao longo do tempo.",

        "funcao": x**2,

        "a": 0,
        "b": 2,

        "pergunta":
            "Calcule a quantidade total "
            "de dados acumulados entre "
            "0h e 2h.",

        "pontos": 100
    },

    2: {
        "nome": "TABELAS FRAGMENTADAS",

        "historia":
            "Fragmentos do banco precisam "
            "ser reconstruídos.",

        "enunciado":
            "A taxa de recuperação de dados "
            "das tabelas é dada pela função:",

        "funcao": 3*x**2 + 5,

        "a": 1,
        "b": 3,

        "pergunta":
            "Determine o total de registros "
            "recuperados entre 1h e 3h.",

        "pontos": 150
    },

    3: {
        "nome": "FIREWALL MATEMÁTICO",

        "historia":
            "Um firewall inteligente bloqueia "
            "o acesso ao núcleo do sistema.",

        "enunciado":
            "A taxa de tráfego de pacotes "
            "recebidos pelo firewall é:",

        "funcao": 3/x + x**2,

        "a": 1,
        "b": 2,

        "pergunta":
            "Calcule o total de pacotes "
            "processados pelo firewall.",

        "pontos": 250
    },

    4: {
        "nome": "NÚCLEO DE DESCRIPTOGRAFIA",

        "historia":
            "A criptografia do sistema usa "
            "integração por substituição.",

        "enunciado":
            "A taxa de descriptografia "
            "dos dados é modelada por:",

        "funcao": 2*x*(x**2 + 1)**5,

        "a": 0,
        "b": 1,

        "pergunta":
            "Determine o volume total "
            "de dados descriptografados.",

        "pontos": 500,

        "substituicao": True,

        "u_correto": "x**2 + 1"
    },

    5: {
        "nome": "MAINFRAME CENTRAL",

        "historia":
            "O núcleo do servidor requer "
            "integração por partes.",

        "enunciado":
            "A taxa de sincronização "
            "dos processos do mainframe é:",

        "funcao": x*sp.exp(x),

        "a": 0,
        "b": 1,

        "pergunta":
            "Calcule o total de processos "
            "sincronizados.",

        "pontos": 1000,

        "partes": True,

        "u_correto": "x",

        "dv_correto": "exp(x)"
    },

    6: {
        "nome": "PROCESSAMENTO DE REGISTROS",

        "historia":
            "Os servidores da corporação "
            "estão sobrecarregados.",

        "enunciado":
            "Uma central de banco de dados "
            "monitora a taxa de transferência "
            "de registros entre servidores.",

        "funcao": -0.02*x**2 + 0.14*x + 1.96,

        "a": 8,
        "b": 20,

        "pergunta":
            "Qual foi a quantidade total "
            "de registros processados "
            "entre 8h e 20h?",

        "pontos": 300
    },

    7: {
        "nome": "EXPANSÃO DE CACHE",

        "historia":
            "O cache distribuído da rede "
            "está crescendo rapidamente.",

        "enunciado":
            "A taxa de crescimento do cache "
            "de consultas do banco é:",

        "funcao": -0.005*x**2 + 0.2*x + 1.5,

        "a": 6,
        "b": 18,

        "pergunta":
            "Determine o crescimento total "
            "do cache entre 6h e 18h.",

        "pontos": 350
    },

    8: {
        "nome": "TRÁFEGO DO FIREWALL",

        "historia":
            "O sistema detectou um ataque "
            "cibernético massivo.",

        "enunciado":
            "A taxa de entrada de pacotes "
            "no firewall é dada por:",

        "funcao": -0.01*x**2 + 0.18*x + 2,

        "a": 4,
        "b": 16,

        "pergunta":
            "Calcule o total de pacotes "
            "recebidos durante o ataque.",

        "pontos": 400
    },

    9: {
        "nome": "BACKUP AUTOMÁTICO",

        "historia":
            "O sistema iniciou um backup "
            "de emergência.",

        "enunciado":
            "A velocidade de transferência "
            "de dados do backup é:",

        "funcao": 0.5*x + 3,

        "a": 2,
        "b": 8,

        "pergunta":
            "Determine o volume total "
            "de dados transferidos.",

        "pontos": 450
    },

    10: {
        "nome": "INGESTÃO BIG DATA",

        "historia":
            "A IA central está absorvendo "
            "dados exponencialmente.",

        "enunciado":
            "A taxa de ingestão de dados "
            "do sistema de IA é dada por:",

        "funcao": 4*sp.exp(0.1*x),

        "a": 0,
        "b": 5,

        "pergunta":
            "Calcule a quantidade total "
            "de dados ingeridos pelo sistema.",

        "pontos": 700
    }

}

# =====================================================
# GAME OVER
# =====================================================

if st.session_state.vidas <= 0:

    st.error("☠️ SISTEMA COMPROMETIDO")
    st.stop()

# =====================================================
# FINAL
# =====================================================

if st.session_state.fase > len(fases):

    st.success("👑 MAINFRAME RESTAURADO")

    st.write(
        f"Pontuação Final: "
        f"{st.session_state.pontos}"
    )

    if st.session_state.pontos >= 1800:

        st.success(
            "🏆 RANK S — ANALISTA LENDÁRIO"
        )

    elif st.session_state.pontos >= 1200:

        st.success(
            "🥇 RANK A — ESPECIALISTA"
        )

    else:

        st.success(
            "🥈 RANK B — ANALISTA"
        )

    st.balloons()

    st.stop()

# =====================================================
# FASE ATUAL
# =====================================================

fase = fases[st.session_state.fase]

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.title("💾 STATUS")

st.sidebar.metric(
    "Fase",
    st.session_state.fase
)

st.sidebar.metric(
    "Pontos",
    st.session_state.pontos
)

st.sidebar.metric(
    "Vidas",
    st.session_state.vidas
)

# =====================================================
# TÍTULO
# =====================================================

st.title("💾 INTEGRALDB")

st.subheader(
    f"🔥 FASE {st.session_state.fase} — "
    f"{fase['nome']}"
)

# =====================================================
# HISTÓRIA
# =====================================================

st.write(fase["historia"])

# =====================================================
# ENUNCIADO
# =====================================================

st.write(fase["enunciado"])

# =====================================================
# INTEGRAL
# =====================================================

st.latex(
    sp.latex(
        sp.Integral(
            fase["funcao"],
            (x, fase["a"], fase["b"])
        )
    )
)

# =====================================================
# PERGUNTA
# =====================================================

st.write(fase["pergunta"])

# =====================================================
# GRÁFICO
# =====================================================

f = sp.lambdify(
    x,
    fase["funcao"],
    "numpy"
)

x_vals = np.linspace(
    fase["a"],
    fase["b"],
    400
)

y_vals = f(x_vals)

fig, ax = plt.subplots(figsize=(8,4))

ax.plot(x_vals, y_vals)

ax.fill_between(
    x_vals,
    y_vals,
    alpha=0.3
)

ax.set_title("Área Sob a Curva")

ax.grid()

st.pyplot(fig)

# =====================================================
# INSTRUÇÕES
# =====================================================

st.info(
    "📌 Digite apenas valores numéricos "
    "com até 2 casas decimais."
)

# =====================================================
# SUBSTITUIÇÃO
# =====================================================

escolha_u = None

if "substituicao" in fase:

    escolha_u = st.radio(
        "Escolha u:",
        [
            "x**2 + 1",
            "2*x",
            "x**5"
        ]
    )

# =====================================================
# POR PARTES
# =====================================================

escolha_u_partes = None
escolha_dv = None

if "partes" in fase:

    escolha_u_partes = st.radio(
        "Escolha u:",
        [
            "x",
            "exp(x)"
        ]
    )

    escolha_dv = st.radio(
        "Escolha dv:",
        [
            "x",
            "exp(x)"
        ]
    )

# =====================================================
# INPUT
# =====================================================

resposta = st.text_input(
    "Digite sua resposta:"
)

# =====================================================
# BOTÃO
# =====================================================

if st.button("Enviar"):

    try:

        resposta = resposta.replace("^", "**")

        resposta_usuario = round(
            float(
                sp.sympify(resposta)
            ),
            2
        )

        valor_correto = round(
            float(
                sp.integrate(
                    fase["funcao"],
                    (
                        x,
                        fase["a"],
                        fase["b"]
                    )
                )
            ),
            2
        )

        correto = abs(
            resposta_usuario
            - valor_correto
        ) < 0.1

        # =============================================
        # SUBSTITUIÇÃO
        # =============================================

        if "substituicao" in fase:

            correto = (
                correto and
                escolha_u
                == fase["u_correto"]
            )

        # =============================================
        # POR PARTES
        # =============================================

        if "partes" in fase:

            correto = (
                correto and
                escolha_u_partes
                == fase["u_correto"]
                and
                escolha_dv
                == fase["dv_correto"]
            )

        # =============================================
        # RESULTADO
        # =============================================

        if correto:

            st.success(
                "✅ ÁREA DESCRIPTOGRAFADA"
            )

            st.write(
                f"Valor correto: "
                f"{valor_correto}"
            )

            st.session_state.pontos += (
                fase["pontos"]
            )

            st.session_state.fase += 1

            st.rerun()

        else:

            st.error(
                "❌ CÁLCULO INCORRETO"
            )

            st.write(
                f"Resposta correta: "
                f"{valor_correto}"
            )

            st.session_state.vidas -= 1

    except:

        st.warning(
            "⚠️ Expressão inválida."
        )